// src/ui/board/bid.jsx
/// <reference path="../../_references.d.ts" />

import React from 'react';
import {BidType, BidSuit, Bid} from '../../model/core/bid';

export class BidComponent extends React.Component {

    constructor(props) {
      super(props);
      console.log('creating bid');
    }

    static key(bid) {
      switch(bid.type) {
        case BidType.NoBid:
          return "No Bid";
        case BidType.Call:
          return bid.level.toString() + bid.suit.toString();
        case BidType.Double:
          return "Double";
        case BidType.Redouble:
          return "Redouble";
        default:
          throw new Error("unrecognised bid");
      }
    }

    render() {
      switch(this.props.bid.type) {
        case BidType.NoBid:
          return <div className="bid-container">No Bid</div>;
        case BidType.Call:
          return (
            <div className="bid-container">
              <span className="bid-level">{this.props.bid.level}</span>
              <span className="bid-suit suit-{this.props.bid.suit}"></span>
            </div>
        );
        case BidType.Double:
          return <div className="bid-container">Double</div>;
        case BidType.Redouble:
          return <div className="bid-container">Redouble</div>;
        default:
           throw new Error("unrecognised bid");
      }
    }
}

// src/solid/components/Bid.tsx
import { Component, Match, Switch } from 'solid-js'
import { Bid, BidType } from '../../model/core/bid';
import "./Bid.css"
import "./Suit.css"

export interface BidProps {
	bid: Bid;
}

export const BidComponent: Component<BidProps> = ({
	bid
}) => {
	return (
		<Switch>
			<Match when={bid.type === BidType.NoBid}>
				<div class="bid-container">No Bid</div>;
			</Match>
			<Match when={bid.type === BidType.Call && bid}>
				{(bid) => <div class="bid-container">
					<span class="bid-level">{bid.level}</span>
					<span class={"bid-suit suit-" + Bid.suitName(bid.suit)}></span>
				</div>}
			</Match>
			<Match when={bid.type === BidType.Double}>
				<div class="bid-container">Double</div>;
			</Match>
			<Match when={bid.type === BidType.Redouble}>
				<div class="bid-container">Redouble</div>;
			</Match>
		</Switch>
	)
}
