// src/ui/components/card.jsx
/* @flow */

import React from 'react';
import {Suit,Pip,Card} from "../../model/core/card";

export class CardComponent extends React.Component {

    constructor(props) {
      super(props);
    }

    static key(card) {
      return Card.suitName(card.suit) + Card.pipName(card.pip);
    }

    render() {
      if (!this.props.card)
         return <div className="card-container empty-container"/>;

      return (
        <div className="card-container">
            <div className="card-edge-left">
                <div className="card-pip-small">{Card.pipName(this.props.card.pip)}</div>
                <div className={"card-suit suit-" + Card.suitName(this.props.card.suit)}></div>
            </div>

            <div className="card-pip">{Card.pipName(this.props.card.pip)}</div>

            <div className="card-edge-right">
                <div className="card-pip-small">{Card.pipName(this.props.card.pip)}</div>
                <div className={"card-suit suit-" + Card.suitName(this.props.card.suit)}></div>
            </div>
        </div>
      );
    }
}

// src/solid/components/Card.tsx
import { Component, Match, Switch } from 'solid-js'
import { Card } from '../../model/core/card';
import "./Card.css"
import "./Suit.css"

export interface CardProps {
	card: Card;
}

export const CardComponent: Component<CardProps> = ({
	card
}) => {
	if (!card)
		return <div class="card-container empty-container"/>;

	return (
		<div class="card-container">
			<div class="card-edge-left">
				<div class="card-pip-small">{Card.pipName(card.pip)}</div>
				<div class={"card-suit suit-" + Card.suitName(card.suit)}></div>
			</div>

			<div class="card-pip">{Card.pipName(card.pip)}</div>

			<div class="card-edge-right">
				<div class="card-pip-small">{Card.pipName(card.pip)}</div>
				<div class={"card-suit suit-" + Card.suitName(card.suit)}></div>
			</div>
		</div>
	);
}
