// src/ui/player/bidding-box.jsx
/// <reference path="../../_references.d.ts" />

import React from 'react';
import {BidComponent} from '../board/bid.jsx';
import {BidSuit, BidType, Bid} from '../../model/core/bid';
import {GameActions} from '../../model/game/game-store';

export class BiddingBox extends React.Component {

   constructor(props) {
      super(props);
      console.log('created bidding-box')
   }

   bidButton(bid: tower.IBid, colspan: number) {
      return (
         <td key={BidComponent.key(bid)} className="bidding-box-cell" colSpan={colspan}>
            <button className="bidding-box-button md-raised"
                    onClick={() => this.makeBid(bid)}>
               <BidComponent bid={bid}/>
            </button>
         </td>
      );
   }

   makeBid(bid) {
      console.log('in makeBid');
      GameActions.makeBid(bid);
      //var newstate = this.props.game.makeBid(bid);
      //this.props.onGameStateChanged(newstate);
   }

   render() {
      console.log('rendering bidding-box');
      var levels = [];
      for (let i = 1; i <= 7; i++) {
         let cells = [];
         for (var s = BidSuit.Clubs; s <= BidSuit.NoTrumps; s ++) {
            cells.push(this.bidButton({type: BidType.Call, suit: s, level: i}, 2));
         }

         levels.push(<tr key={i} className="bidding-box-level">{cells}</tr>);
      }
      var modButtons = [
         this.bidButton({type: BidType.Double}, 3),
         this.bidButton({type: BidType.Redouble}, 3),
         this.bidButton({type: BidType.NoBid}, 4)
      ];

      levels.push(
         <tr key="bottom" className="bidding-box-level">
            {modButtons}
         </tr>
      );

      return (
         <div className="bidding-box-container">
            <table>
               <colgroup>
                  <col span="1" style={{width: '10%'}}></col>
                  <col span="1" style={{width: '10%'}}></col>
                  <col span="1" style={{width: '10%'}}></col>
                  <col span="1" style={{width: '10%'}}></col>
                  <col span="1" style={{width: '10%'}}></col>
                  <col span="1" style={{width: '10%'}}></col>
                  <col span="1" style={{width: '10%'}}></col>
                  <col span="1" style={{width: '10%'}}></col>
                  <col span="1" style={{width: '10%'}}></col>
                  <col span="1" style={{width: '10%'}}></col>
               </colgroup>
                  <tbody>
                     {levels}
                  </tbody>
            </table>
         </div>
      );
   }
}

// src/solid/table/BiddingBox.tsx
import { Component, For } from 'solid-js'
import { BidComponent } from '../components/bid.jsx';
import { Bid, BidSuit, BidType } from '../../model/core/bid';
import "./BiddingBox.css"

export interface BiddingBoxProps {
	makeBid: (bid: Bid) => void;
}

export const BiddingBox: Component<BiddingBoxProps> = ({
	makeBid
}) => {
	return (
		<div class="bidding-box-container">
			<For each={[1, 2, 3, 4, 5, 6, 7]}>
				{(level) => (
					<div class="bidding-box-row">
						<For each={BidSuit.all()}>
							{(suit) => (
								<BidButton bid={{ type: BidType.Call, level, suit }} makeBid={makeBid} />
							)}
						</For>
					</div>
				)}
			</For>
			<div class="bidding-box-row">
				<BidButton bid={{ type: BidType.NoBid }} makeBid={makeBid} />
				<BidButton bid={{ type: BidType.Double }} makeBid={makeBid} />
				<BidButton bid={{ type: BidType.Redouble }} makeBid={makeBid} />
			</div>
		</div>
	);
}

interface BidButtonProps {
	bid: Bid;
	makeBid: (bid: Bid) => void;
}

const BidButton: Component<BidButtonProps> = ({
	bid,
	makeBid
}) => {
	return (
		<button class="bidding-box-button pure-button" classList={{
			"bidding-box-button-special": bid.type !== BidType.Call
		}}
			onClick={() => makeBid(bid)}>
			<BidComponent bid={bid} />
		</button>
	);
}
