// src/solid/table/BiddingHistory.tsx
import { Component, For, Show } from 'solid-js'
import { BidComponent } from '../components/bid.jsx';
import { Seat } from '../../model/core/seat.js';
import { GameState } from './gameStore.js';
import "./BiddingBox.css"

export interface BiddingHistoryProps {
	gameState: GameState;
}

export const BiddingHistory: Component<BiddingHistoryProps> = ({
	gameState
}) => {
	const boardState = gameState.boards[gameState.boards.length - 1];

	return (
		<table class="bidding-container pure-table">
			<thead>
				<tr>
					<For each={Seat.all()}>
						{(seat) => <th class="bidding-cell">{Seat.name(seat)}</th>}
					</For>
				</tr>
			</thead>
			<tbody>
				<For each={[0, 1, 2, 3, 4, 5, 6]}>
					{(rowIdx) => (
						<tr class="bidding-round">
							<For each={Seat.all()}>
								{(seat) => {
									const position = (rowIdx * 4) + seat;
									const bid = boardState.bids[position];
									return (<td class="bidding-cell">
										<Show when={bid}>
											<BidComponent bid={bid} />
										</Show>
									</td>)
								}}
							</For>
						</tr>
					)}
				</For>
			</tbody>
		</table>
	);
}

// src/ui/table/bidding-history.jsx
/* @flow */

import React, {Component, PropTypes} from 'react';

import {BidComponent} from '../components/bid.jsx';
import {Seat} from '../../model/core/seat';
import './bidding-history.css';

export class BiddingHistory extends Component {

	constructor(props) {
		super(props);
	}

	static propTypes = {
		board: PropTypes.object.isRequired
  	};

	render() {
		let headings = [];

		for (let seat = Seat.North; seat <= Seat.West; seat ++) {
			headings.push(
				<th key={seat} className="bidding-cell">{Seat.name(seat)}</th>
			);
		}

		let rows = [];

		for (let i = 0; i < 6; i ++) {
			let cells = [];

			for (let j = 0; j < 4; j ++) {
				let position = (i * 4) + j;

				if (this.props.board.bids.length > position) {
					let bid = this.props.board.bids[position];
					cells.push(
						<td key={position} className="bidding-cell">
							<BidComponent bid={bid}/>
						</td>
					);
				}
				else {
					cells.push(<td key={position} className="bidding-cell"></td>);
				}
			}
			rows.push(
				<tr key={i} className="bidding-round">
					{cells}
				</tr>
			);
		}

		return (
			<table className="bidding-container pure-table">
				<thead>
					<tr>{headings}</tr>
				</thead>
				<tbody>
					{rows}
				</tbody>
			</table>
		);
	}
}
